### ISSUE TITLE
Cannot complete a purchase

### ISSUE THREAD

**Issue by capossele** [FIWARE-TMForum/Business-API-Ecosystem#10]
Hi all,
I am working with the BAE version 6.4.0 (have adapted the docker compose file to retrieve the v6.4.0 version of each docker build). Whenever I try to purchase a digital asset (whether for free or with a price plan) I got an error "Your order could not be processed". I past the output of tcpdump listening on the charging backend:

`POST /charging/api/orderManagement/orders HTTP/1.1
content-type: application/json
accept: application/json
Authorization: Bearer B80xgVLgHNq2W0aPjkpAxpUjLxtWYf
X-Nick-Name: buyer
X-Email: angelo@email.com
X-Display-Name: buyer
X-Roles: 
X-Actor: buyer
host: charging.docker:8006
content-length: 1558
Connection: close

{"id":364,"href":"http://127.0.0.1:8004/DSProductOrdering/api/productOrdering/v2/productOrder/364","priority":"4","category":"uncategorized","state":"Acknowledged","orderDate":"2018-03-13T17:42:57Z","completionDate":null,"requestedStartDate":"2018-03-13T17:43:14Z","requestedCompletionDate":"2018-03-13T17:43:14Z","expectedCompletionDate":null,"notificationContact":"a@b.c","note":[],"relatedParty":[{"id":"buyer","href":"http://127.0.0.1:8004/DSPartyManagement/api/partyManagement/v2/individual/buyer","role":"Customer"},{"id":"dan","href":"http://127.0.0.1:8004/DSPartyManagement/api/partyManagement/v2/individual/dan","role":"Seller"}],"orderItem":[{"id":"0","action":"add","state":"Acknowledged","billingAccount":[{"id":"1","href":"http://127.0.0.1:8004/DSBillingManagement/api/billingManagement/v2/billingAccount/1"}],"productOffering":{"id":"57","href":"http://127.0.0.1:8004/DSProductCatalog/api/catalogManagement/v2/catalog/1/productOffering/57"},"product":{"startDate":null,"orderDate":null,"terminationDate":null,"productCharacteristic":[{"name":"Asset type","value":"Basic Service"},{"name":"Media type","value":"mu"},{"name":"Location","value":"http://www.u.com"}],"productRelationship":[],"billingAccount":[],"relatedParty":[{"id":"buyer","role":"Customer","href":"http://127.0.0.1:8004/DSPartyManagement/api/partyManagement/v2/individual/buyer"},{"id":"dan","role":"Seller","href":"http://127.0.0.1:8004/DSPartyManagement/api/partyManagement/v2/individual/dan"}],"realizingResource":[],"realizingService":[],"productPrice":[],"agreement":[]}}]}

17:43:15.308531 IP 31455b529bae.8006 > compose_proxy_1.main.48696: Flags [P.], seq 1:259, ack 1897, win 256, options [nop,nop,TS val 22055198 ecr 22055171], length 258
E..6A.@.@............F.8....v.......YZ.....
.P...P..HTTP/1.1 500 INTERNAL SERVER ERROR
Date: Tue, 13 Mar 2018 17:43:15 GMT
Server: Apache/2.4.18 (Ubuntu)
Content-Length: 65
Connection: close
Content-Type: application/json; charset=utf-8

{"result": "error", "error": "Your order could not be processed"}`

Do you have experienced a similar issue before?

**Comment by fdelavega** [comment]
Hi,

This could happen if the URL of the services configured in services_setting.py are not completely correct, so the charging backend cannot access to the catalog or billing API.

Try to check the URLs and ensure they are accessible from the charging backend container
