### ISSUE TITLE
The server has failed validating the product specification

### ISSUE THREAD

**Issue by pacasa2** [FIWARE-TMForum/Business-API-Ecosystem#13]
Hi!
I'm trying to create a Product Specification in my new deployed BAE and I am getting the following error:
> {"error":"The server has failed validating the product specification"}

I am trying to create the Specification via Web Portal and via API Rest, and both methods throw the same error.
My installed version of the BAE is 6.4.0, deployed in a Virtual Machine at FIWARE Cloud.

I don't know if it could be a configuration problem or a bug..

**Comment by pacasa2** [comment]
I am trying with an instance with 5.4.1 version deployed and I'm having the same problem

**Comment by fdelavega** [comment]
That error means that some kind of unexpected exception happened at the charging backend component.

Did you update from the 5.4.1 or did you install the 6.4.0 directly?

On the other hand, is the product digital, and if so, what is the asset type of the product you are trying to create?

Did you review the configuration section of the 6.4.0 documentation, there are some new stuff that may not be properly configured is reusing the documentation of 5.4.1

**Comment by pacasa2** [comment]
-The error is happening with 6.4.0 version freshly installed and in 5.4.1 version(without updating).
-Error persists in both digital and non digital product specifications. 
- The configuration of the 5.4.1 version was made some months ago, when the documentation was refered to that version. My instance of 6.4.0 has been installed and configured with the latest version of the documentation.

I am running the charging backend with Django runserver command, if this information can help...

**Comment by fdelavega** [comment]
The runserver should not be an issue. Maybe is some kind of communication issue, I guess you are using localhost as configuration of the different components in services_settings.py, aren't you?

On the other hand, did you made a deployment based in sources or using the docker images?

**Comment by pacasa2** [comment]
Yes, I am using localhost as the configuration in services_settings.py.
I've made the deployment from sources following  the installation guide

**Comment by pacasa2** [comment]
any hint about which could be the problem?

**Comment by fdelavega** [comment]
Can you check if the Catalog API is up and running?

**Comment by pacasa2** [comment]
How can i check that?

**Comment by fdelavega** [comment]
wget http://localhost:8080/DSProductCatalog

**Comment by fdelavega** [comment]
I am closing the issue, please reopen if the problem persist
