### ISSUE TITLE
Organization roles are ignored

### ISSUE THREAD

**Issue by emepetres** [FIWARE-TMForum/Business-API-Ecosystem#17]
Users roles are ignored when assigned through an organization:

An user that is a member of an organization which is authorised in a certain application with seller role, appears in the web interface as no seller. However if you authorise the user directly in the application with the seller role, this user appears as a seller in the biz web interface.

**Comment by fdelavega** [comment]
Organizations are like other users of the system. If you want a user to make actions on behalf an organization he belongs, you have to click in their username to see the dropdown menu and thn swich session to the organization you want

If the user has the seller role within the organization he will be then able to create organization offerings

Note that a user may be seller in an organization and not be seller at app level

**Comment by emepetres** [comment]
Ok I understands, thanks!
