### ISSUE TITLE
DSProductInventory error: You are not authorized to retrieve the orderings made by the user X

### ISSUE THREAD

**Issue by emepetres** [FIWARE-TMForum/Business-API-Ecosystem#19]
I can't access to Inventory Management API, while I can access to the Catalogue Management API using the same token. I'm using IDM v7, and latest develop docker images for the BIZ. I'm getting a 403 with the following body:
```
{ 
   "error": "You are not authorized to retrieve the orderings made by the user jcarnero"
}
```

**Comment by fdelavega** [comment]
I think that this problem is generated for the same reason (different hrefs) as #18

**Comment by emepetres** [comment]
Still with the issue, after modifying server property in apis-conf/settings-properties file from `http://proxy.docker:8004/` to `http://[DOCKER_MACHINE_HOST]:8004/`

Below the proxy log (To test I used postman from my local computer):
```
2018-05-16 15:21:19.013  - WARN: Server - 51f49039-dcec-4ed2-8ed3-7f0f18ebb217 - ::ffff:10.38.0.1 - Anonymous - GET: /DSProductInventory/api/productInventory/v2/product?status=active&relatedParty.id=jcarnero - Token 6451599ae38e74508a6c929a6bdcb54a895aff80 is from a different app
2018-05-16 15:21:19.046  - WARN: TMF - 51f49039-dcec-4ed2-8ed3-7f0f18ebb217 - ::ffff:10.38.0.1 - f8297ebc-4a60-4a43-9d74-cec472bbc01f - GET: /DSProductInventory/api/productInventory/v2/product?status=active&relatedParty.id=jcarnero - Pre-Validation (DSProductInventory): You are not authorized to retrieve the orderings made by the user jcarnero
2018-05-16 15:21:19.052  - WARN: Server - 51f49039-dcec-4ed2-8ed3-7f0f18ebb217 - ::ffff:10.38.0.1 - f8297ebc-4a60-4a43-9d74-cec472bbc01f - GET: /DSProductInventory/api/productInventory/v2/product?status=active&relatedParty.id=jcarnero - Status: 403
```

**Comment by fdelavega** [comment]
um, that should'n be a problem, the BAE detects that the token is for an external application and uses the refresh token of the last session to obtain valid user info for the BAE app

**Comment by fdelavega** [comment]
Just a question, can you access to other protected information?
For example to the ordering API, etc

**Comment by fdelavega** [comment]
Well reviewing the code, the error happens when the query string (filter) relatedParty.id is different from the req.user.id which is populated using the information of the user given by the IDM.

According to the error message you are facing, relatedParty.id = jcarnero

So, is it possible that the access token you are sending to the BAE belongs to a user different from jcarnero?

**Comment by emepetres** [comment]
Ok, I think I found the problem.

Indeed if I remove `relatedParty.id` I don't get the error. The same happens wih orderint API.

_jcarnero_ is the user name on the IDM, and it also appears on the top right corner of the web interface of the BIZ. In the old IDM v5 `displayName` and `id` properties returned the same value, but in IDM v7 `id` a returns a hash code.

Following your previous comment, if I do `relatedParty.id=jcarnero` it fails, but if I do `relatedParty.id=f8297ebc-4a60-4a43-9d74-cec472bbc01f` it works!

Summarizing, I think that to resolve this issue, docs should be modified to specify that `relatedParty.id` doesn't use the user name any more, and instead the IDM id user which is a code (something like that, to prevent confusions with old IDM v5)

**Comment by fdelavega** [comment]
buf, this change in the IDM v7 is going to be weird in new deployments and a real problem in migrations. I mean the failure is going to happen when migrating from v6 to v7 in a working BAE instance
