### ISSUE TITLE
Showing user hash (new IDM id) on product order

### ISSUE THREAD

**Issue by emepetres** [FIWARE-TMForum/Business-API-Ecosystem#20]
Following on #19, on a product order the customer id is shown, which with the new IDM is a hash code.

It should be shown the property 'displayName' instead of 'id'.

In the following issue there is an screenshot of the problem:
https://github.com/MSO4SC/MSOPortal/issues/63

**Comment by fdelavega** [comment]
I have update the order interface so it displays the user or organization names rather than the ID, the change is in develop branch and updated in the develop docker of the proxy

Let me know if you have any issue with this

**Comment by emepetres** [comment]
Thanks!
