### ISSUE TITLE
How to create and manage organisation?

### ISSUE THREAD

**Issue by Trophime** [FIWARE-TMForum/Business-API-Ecosystem#23]
Hi,
in the frame of [MSO4SC project](https://github.com/MSO4SC/MSOPortal/tree/master/marketplace) we are using MarketPlace.

I would like to create and manage Organisation but I cannot find any docs on these topics.
I must have read througth the docs too quickly...

Could you point me to some documents?

**Comment by fdelavega** [comment]
BAE organizations are managed in the IDM, so when you assign any BAE role to a user within an organization, then the user can switch to that organization in the BAE interface.

If you assign the seller role in an organization, then that user can create offerings on behalf that organization, the same for customer role.

In addition, the BAE in the IDM should define an orgAdmin role which allows to specify who are the admin of organizations in the BAE (for example to setup organization billing address)
