### ISSUE TITLE
Purchase is stucked

### ISSUE THREAD

**Issue by emepetres** [FIWARE-TMForum/Business-API-Ecosystem#25]
The following purchase is in status "In progress", but in the button is "Delivered". "Reject" seems to do nothing. The user never received the product in its inventory.

<img width="776" alt="marketplace_bug" src="https://user-images.githubusercontent.com/1446793/41289829-52325ff0-6e4b-11e8-8f19-6176359a278a.png">

**Comment by fdelavega** [comment]
Is this problem still persisting? it is giving an error?

**Comment by emepetres** [comment]
We just deleted the databases, but probably it will arise again
