### ISSUE TITLE
"Recibidas" button don't change its language.

### ISSUE THREAD

**Issue by emepetres** [FIWARE-TMForum/Business-API-Ecosystem#26]
On "My Inventory", button "Recibidas" stays in spanish when the language changes to english.

<img width="776" alt="marketplace_bug" src="https://user-images.githubusercontent.com/1446793/41289951-a45ee4ec-6e4b-11e8-96a1-23d920ca5a5a.png">

**Comment by fdelavega** [comment]
This issue should be fixed now
