### ISSUE TITLE
Personal settings "user name" showing a hash

### ISSUE THREAD

**Issue by emepetres** [FIWARE-TMForum/Business-API-Ecosystem#28]
In personal settings, the user name is a hash (it is showing the IDM "id" while it should be showing the "displayName".

![marketplace_bug](https://user-images.githubusercontent.com/1446793/41337357-4b0513a4-6eef-11e8-8f24-3df18bc55ed3.png)

**Comment by fdelavega** [comment]
The problem we faced is that the TMForum standard we are using for storing user info in the BAE do not include a username field, only the ID, when the IDM used the username as a ID there were no problem, but now we have this weird thing

**Comment by fdelavega** [comment]
This is fixed in current version, please reopen if you found this again
