### ISSUE TITLE
How to assign the seller role?

### ISSUE THREAD

**Issue by jivung** [FIWARE-TMForum/Business-API-Ecosystem#33]
How do I assign the seller role to a user of an BAE application? I've read the docs put can't find it anywhere. I've looked in both the BAE and the IdM but I can't find the Seller role, only provider and purchaser.

I'm running a private BAE with docker and using the online lab IdM.

**Comment by fdelavega** [comment]
The provider and purchaser roles are IdM roles. The IdM is not coupled with the different systems, instead it allows to create custom roles. For the particular case of the BAE you need to create the different roles using the create role option of the IDM within thr BAE app

**Comment by jivung** [comment]
That solved it, thank you! 
It may be a good idea to explain this in the docs since I don't think it's very obvious.
