### ISSUE TITLE
Create an "admin" user 

### ISSUE THREAD

**Issue by Urtza2** [FIWARE-TMForum/Business-API-Ecosystem#37]
I have create an application in IDM when I have authorize a user with two roles:
-Seller
-Provider

I am not be able to access "Administration" section of the web portal.
How can I do this?

I have to create an organization or what are the steps to do this?, 
is it possible to create an user with two roles?

Thanks in advance
Urtza

**Comment by CTidelius** [comment]
Did you manage to solve this? I cannot access the administration section either.

**Comment by Urtza2** [comment]
Hi CTidelius,
I have done several things but I do not know if they are all necessary, the truth is that it has worked for me.
First of all I have created and application in IDM for BAE. After I click on "manage roles" button and I added "Admin" and "orgAdmin" role. When these roles have been saved you have to click on in "Authorize" buttonh in Authorize Users section and add these new roles to the user.
Now you have to open config.js (bussiness-logic-proxy) and add the IDM application information:

I have the following in Oauth2 section:

// OAuth2 configuration
config.oauth2 = {
    'server': 'https://localhost:8443',
    'clientID': '9b5425d4-41cc-496f-b368-054b64e5e9fd',
    'clientSecret': 'c877e186-1620-476e-89b8-263bb252ffec',
    'callbackURL': 'http://localhost:81/auth/fiware/callback',
    'isLegacy': false,
    'roles': {
    ###     **'admin': 'admin',**
        'customer': 'customer',
        'seller': 'seller',
        **### 'orgAdmin': 'orgAdmin'**
	
    }
};

It is very importart change the value of admin variable in roles. Doing this I solve all of my problems.

Urtza
