### ISSUE TITLE
[SHOULD] Double tag FIWARE Release

### ISSUE THREAD

**Issue by jason-fox** [FIWARE-TMForum/Business-API-Ecosystem#46]
Yes I know the existing version numbers _currently_ align, but could you please add an additional tags to  indicate which version aligns with which  FIWARE  release- you can see a similar examples here:

[IoT Agent JSON](https://github.com/telefonicaid/iotagent-json/releases)

* dd79474 - `FIWARE 7.5.1`, `FIWARE_7.5`, -`FIWARE_7.4`

**Comment by fdelavega** [comment]
I have double tagged release 7.4, do you need me to double tag all existing versions?

**Comment by jason-fox** [comment]
@fdelavega - ideally yes, dd79474 should have 4 tags on it:

* Version 7.4.0 of BAE
* Works with FIWARE_7.4
* Works with FIWARE_7.5
* Works with FIWARE_7.5.1

I don't care about releases before 7.4, because  before the catalogue was moved to GitHub, there was no serious attempt to consistently align product releases (on your side) and what is now defined as a FIWARE release (on our side)

**Comment by fdelavega** [comment]
Ok, understood, I have included them

**Comment by jason-fox** [comment]
👍
