### ISSUE TITLE
[SHOULD] Repo URL link

### ISSUE THREAD

**Issue by jason-fox** [FIWARE-TMForum/Business-API-Ecosystem#47]
Please click the edit button at the head of the repo and amend the link URL as shown:

### Link

> https://business-api-ecosystem.rtfd.io/

- SHOULD requirement from the TSC.

**Comment by fdelavega** [comment]
Do you mean the website input that is included with the repository description?

**Comment by jason-fox** [comment]
Yes, that's the one! Thanks.
