### ISSUE TITLE
[SHOULD] run tests on CI

### ISSUE THREAD

**Issue by jason-fox** [FIWARE-TMForum/Business-API-Ecosystem#48]
There are currently no Unit Tests run on CI on push.

Please either add a test step to the existing travis script or expose test results in some other manner.

- running tests on CI is a SHOULD requirement from TSC
- Adding a Unit test badge/link is a MUST requirement from TSC

**Comment by fdelavega** [comment]
This is not a software repository, software repos belonging to the BAE have both unit ttest in travis and coverage report in coverals and the badge attached to the README file

https://github.com/FIWARE-TMForum/business-ecosystem-logic-proxy
https://github.com/FIWARE-TMForum/business-ecosystem-charging-backend
https://github.com/FIWARE-TMForum/business-ecosystem-rss

Do you think we should copy such badges also in this repo readme file?

**Comment by jason-fox** [comment]
No, that is fine as it is - I just couldn't see any CI Unit Tests (on this repo) and therefore raised an issue.

Looks like it has been raised in error - closing.
