### ISSUE TITLE
Market place unstable and degrades after some time

### ISSUE THREAD

**Issue by contrasec-fi** [FIWARE-TMForum/Business-API-Ecosystem#64]
Hi,

firstly, I'll update the issue later with relevant info, so dont crucify me for crappy issue yet. 

Problem that we are seeing is that after the setup and operating for some time (> days ) it's not possible to move offerings from one state to another. We tried to promote an offering from Created to Active, but it fails (no error in UI) and offer stays in created state:

![image](https://github.com/FIWARE-TMForum/Business-API-Ecosystem/assets/87982382/ed9cf19c-53d1-4999-8b39-777d23343b41)

we are running on K8S, and have the i4Trust plugins in place.

**Comment by fdelavega** [comment]
Hi,

One question, when you try to update the status, did you get an error from the backend or it just doesn't do anything?

Is there enougth available space free in the disk? I am mentioning this as the BAE uses Elasticsearch for powering all the queries done from the portal, and it automatically sets to readonly when there is less than 20% of disk available  (see [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-blocks.html#:~:text=Elasticsearch%20adds%20the%20read%2Donly,watermark%2C%20controlled%20by%20the%20cluster.))

**Comment by ilarimikkonen** [comment]
Hi,

we had to update the certificates and redeploy the whole thing - now it works. You can close this @fdelavega i'll open a new one if we can repro the issue. sorry.

**Comment by fdelavega** [comment]
ok, thanks!
