### ISSUE TITLE
I can't complete my order

### ISSUE THREAD

**Issue by lab-project** [FIWARE-TMForum/Business-API-Ecosystem#9]
Hi, 
      I'm using the last release of Business-API-Ecosystem but I can't checkout because of the following error:
"There was an error at the time of retrieving the Billing Address".

Thanks for your attention. I’m looking forward to your reply.

![issue_640](https://user-images.githubusercontent.com/36042623/35686560-d2c66f08-076c-11e8-88b0-4edac9108d11.jpg)
![issue_640_2](https://user-images.githubusercontent.com/36042623/35686561-d2e2fcb8-076c-11e8-82d2-4ac190aa33d6.jpg)

**Comment by fdelavega** [comment]
Um, it seems that the Billing API cannot be reached, can you ensure that it is up and running and review the configuration of the API, both in config.js (proxy) and services_settings.py (charging backend)

**Comment by fdelavega** [comment]
I am closing the issue, please reopen if the problem persists
